### ISSUE TITLE
Wrong solution in sequence models' notebook exercise 2.10

### ISSUE THREAD

**Issue by JoaoLages** [LxMLS/lxmls-toolkit#102]
In [labs/notebooks/sequence_models/Exercises_2.1_to_2.11.ipynb](https://github.com/LxMLS/lxmls-toolkit/blob/master/labs/notebooks/sequence_models/Exercises_2.1_to_2.11.ipynb) the solution to the exercise 2.10 shows the function `train_EM` when the objective was to construct the `update_counts`function instead.

**Comment by JoaoLages** [comment]
The headline of Exercise 2.11 should be change to 'Run 20 epochs of the EM algorithm for part of speech induction.' also.

**Comment by ramon-astudillo** [comment]
Thanks @JoaoLages can you make a PR with these changes to `develop`?

**Comment by JoaoLages** [comment]
Sure. Should only be this #106
