### ISSUE TITLE
solve.py is not compatible with Python3

### ISSUE THREAD

**Issue by aliskin** [LxMLS/lxmls-toolkit#103]
solve.py script in the branch  `student` is not compatible with Python3 in several aspects:
- raising exceptions
- calling print function
- urllib2.urlopen is replaced with urllib.request.urlopen

On the other hand, in the lab guide the students are expected to use Python3, that's why I propose to fix solve.py and make it Python3-compatible. I've already fixed the above issues locally but I don't feel confident enough to make a pull request.

Thanks!

**Comment by ramon-astudillo** [comment]
Thanks!, making a PR is really easy and I think you should do it. Do you need specific guidance?.

**Comment by aliskin** [comment]
Thanks Ramon! I made it :) hope it will be useful.

**Comment by ramon-astudillo** [comment]
Solved by https://github.com/LxMLS/lxmls-toolkit/pull/104 still pending changes in guide
