### ISSUE TITLE
Add autoreload extension to the notebooks when students need to implement code

### ISSUE THREAD

**Issue by dcferreira** [LxMLS/lxmls-toolkit#118]
I think it would be a good idea to add the magic commands to load the autoreload extension, at least for the ``lxmls`` module.

**Comment by ramon-astudillo** [comment]
Is there any downside to this?. Like slower processing?.

**Comment by dcferreira** [comment]
It's probably slower if you enable autoreload for every module, but you can also restrict it to autoreload just ``lxmls``. I guess differences won't be noticeable.

**Comment by ChristopherBrix** [comment]
For reference, this was also mentioned here: https://github.com/LxMLS/lxmls-guide/issues/74

The magic commands are 

```
%load_ext autoreload
%autoreload 2
```

I'm in favor of just reloading everything. It shouldn't hurt the performance too much and ensures everything is working, even if they eg. decide to write their own package.
