### ISSUE TITLE
Encoding needs to be specified everywhere a file is read

### ISSUE THREAD

**Issue by dcferreira** [LxMLS/lxmls-toolkit#124]
The encoding used by ``open()`` in python is platform dependent, so we should specify it everywhere.

@pedrobalage reported this in:
https://github.com/LxMLS/lxmls-toolkit/blob/2250dc212201f4d6bd2d8f4410e841f81bfee6c0/lxmls/parsing/dependency_reader.py#L50

https://github.com/LxMLS/lxmls-toolkit/blob/2250dc212201f4d6bd2d8f4410e841f81bfee6c0/lxmls/parsing/dependency_reader.py#L89

But I guess this happens in more places.

**Comment by ChristopherBrix** [comment]
While we fix this, we should switch from `codecs.open` and `open` to `io.open`, to have one uniform solution for both Py2 and Py3. Once Py2 is no longer supported, we could switch from `io.open` back to `open`.

**Comment by bpopeters** [comment]
Fixed by #222
