### ISSUE TITLE
Some notebooks contain saved output

### ISSUE THREAD

**Issue by ChristopherBrix** [LxMLS/lxmls-toolkit#142]
Some notebooks contain computed output, including customs paths (eg. in the exception message for the [linear classifier notebook](https://github.com/LxMLS/lxmls-toolkit/blob/master/labs/notebooks/linear_classifiers/exercises.ipynb)).

The students can just rerun the cell to get their own output, but this might be a bit confusing.

**Comment by ramon-astudillo** [comment]
Yes, this happens often as people forget to clean the notebooks. Ideally we would clean all content automatically. We are left still with a lot of meta-data changing (Python versions and such).

**Comment by ChristopherBrix** [comment]
Maybe this script could help?: https://gist.github.com/pbugnion/ea2797393033b54674af

I've tried it, and it does remove the output. We could extend it to delete the metadata as well. If I've time tomorrow, I can do this.

**Comment by ramon-astudillo** [comment]
Solved by https://github.com/LxMLS/lxmls-toolkit/pull/151
