### ISSUE TITLE
Dictionary in pos_corpus.py

### ISSUE THREAD

**Issue by tsvm** [LxMLS/lxmls-toolkit#161]
The `read_conll_instances` method in `pos_corpus.py` is adding more words than are actually used, as it seems to be adding the words before checking whether the length of the sentence is within the limit. 
This is not a big problem, but students were trying to understand the word features and it was a little confusing why there were words that do not belong to either train, dev or test.

**Comment by ramon-astudillo** [comment]
Yes, I recall this. Do you see an easy fix?

**Comment by bpopeters** [comment]
As far as I can tell, this has never been fixed. However, it doesn't seem critical to anything going on now.
