### ISSUE TITLE
Day 0: Tests to check installation

### ISSUE THREAD

**Issue by ChristopherBrix** [LxMLS/lxmls-toolkit#166]
I think it would be helpful to include some tests in the notebook for day 0. Some things we know will be needed later on, and that often fail one way or another.

 - Import all used libraries (especially the lxmls package) 
 - Use Matplotlib to display a figure
 - Modify the lxmls package and verify that changes are correctly loaded

This way, we might be able to catch all /most) of those issues within the first day, and don't have to go back to installing stuff on day 2.

We should also explicitly state that the students cannot just move stuff around It's not a good idea to move the location of any folder, as relative imports might fail.

**Comment by pedrobalage** [comment]
We decided to remove day 0 so this issue is no longer.
