### ISSUE TITLE
Problem when installing with pip

### ISSUE THREAD

**Issue by juanmc2005** [LxMLS/lxmls-toolkit#169]
Hello,

After creating a clean conda environment, doing `pip install --editable .` throws the following error :

```
Complete output (12 lines):
    Traceback (most recent call last):
      File "/home/.../lxmls-toolkit/setup.py", line 6, in <module>
        from pip._internal import download
    ImportError: cannot import name 'download'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/../lxmls-toolkit/setup.py", line 8, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I'm running python 3.6 and pip 20.0.2 (also tried python 3.7 and pip 20.1.1 with no success).

Should I downgrade to a specific pip version?

Thank you

**Comment by ramon-astudillo** [comment]
This should be now fixed, thanks @dcferreira

**Comment by juanmc2005** [comment]
Thank you for the fix!

Just to point out that it is currently merged on master but the installation guide says to use the `student` branch. I cherry-picked the commit but it would probably be easier to merge it there as well.

**Comment by ramon-astudillo** [comment]
thanks again @juanmc2005 , this is now pushed to `student` as well
