### ISSUE TITLE
Incorrect guide reference

### ISSUE THREAD

**Issue by Clarkdrengen** [LxMLS/lxmls-toolkit#212]
On page 45 of the guide immediately above equation (2.10) "in a linear way, the second derivative in Eq.2.12 is given by", should be  changed to "in a linear way, the second derivative in Eq.2.9 is given by".

**Comment by g8a9** [comment]
Fixed on the overleaf project. Changes will be reflected [here](https://github.com/LxMLS/lxmls-guide-overleaf)

**Comment by g8a9** [comment]
Fixed on the overleaf project. Changes will be reflected [here](https://github.com/LxMLS/lxmls-guide-overleaf)
