### ISSUE TITLE
MIRA and SVM are implemented in student branch

### ISSUE THREAD

**Issue by beckdaniel** [LxMLS/lxmls-toolkit#35]
According to the guide, the student should implement MIRA and SVM (Exercises 1.3 and 1.5, respectively) but these algorithms are already implemented in the student branch. In fact, they seem to be the same implementations as in the master branch since "git diff master student" doesn't output anything in both mira.py and svm.py.

**Comment by ramon-astudillo** [comment]
Yes, we decided to let these in the student branch as very few students manage to finish these on time. Could you please modify the text of the exercises to reflect this as e.g. Ex. 1.4?

**Comment by ramon-astudillo** [comment]
Fixed

**Comment by dcferreira** [comment]
This issue wasn't fixed in the guide for exercise 1.5 (SVM).
