### ISSUE TITLE
small error on the perceptron code

### ISSUE THREAD

**Issue by davidbp** [LxMLS/lxmls-toolkit#37]
Small "bug" in the perceptron and the Mira algorithms.

The permutation of the data is done at each epoch according to the documentation. Nevertheless  the code performs a permutation to the data that reamins the same across all epochs.

The code is currently:

        # # Randomize the examples
        perm = np.random.permutation(nr_x)
        for epoch_nr in xrange(self.nr_epochs):
            for nr in xrange(nr_x):
                ...

but it should be 

        for epoch_nr in xrange(self.nr_epochs):
            # # Randomize the examples
            perm = np.random.permutation(nr_x)
            for nr in xrange(nr_x):
                ...

The documentation:

![screen shot 2015-05-29 at 21 13 07](https://cloud.githubusercontent.com/assets/4223580/7890653/87f9e956-0647-11e5-8a90-82cd6d9c1d23.png)

**Comment by ramon-astudillo** [comment]
Ok, can you submit the changes?

**Comment by davidbp** [comment]
I've created a pull request. Is this the way you expect to work? 
(opening issue and then creating a pull request with the  bug or suggestion changed)

Pull request

https://github.com/LxMLS/lxmls-toolkit/pull/38


Or would you prefer to generate from the start a pull request explaining the changes?

**Comment by ramon-astudillo** [comment]
Its ok like this.
