### ISSUE TITLE
(Day 5) No en_perline001.txt in the student branch.

### ISSUE THREAD

**Issue by beckdaniel** [LxMLS/lxmls-toolkit#41]
Day 5 guide asks students to run

python wordcount.py en_perline001.txt > results.txt

but there's no file inside the big_data folder. Also, the guide says to navigate to the "wordcount" folder while the script is actually inside the "big_data" folder but this can be easily fixed in the guide.

**Comment by miguelbalmeida** [comment]
The file is in folder data/wikipedia. Earlier editions of LxMLS ran this code on virtual machines where the folder structure was different.

**Comment by miguelbalmeida** [comment]
Daniel, while you're at it, can you change the guide to reflect the correct paths?

**Comment by beckdaniel** [comment]
Yes, I can do it.
