### ISSUE TITLE
emission scores outside the logsum in the backward algorithm ?

### ISSUE THREAD

**Issue by davidbp** [LxMLS/lxmls-toolkit#43]
I find the run_forward and run_backward algorithms  a bit messi since the pseudocode provided uses
probabilities and the code uses scores.

Shouldn't the emission scores be outside the logsum ? 

In the sequence_classification_decoder.py function we have, in run_backward:

backward[pos, current_state] = logsum( backward[pos+1, :] 
                                                                + transition_scores[pos, :, current_state] 
                                                                + emission_scores[pos+1, :])

In the run_forward algorithm we have the emisison_scores OUTSIDE the logsum function

forward[pos, current_state] = logsum(forward[pos-1, :] + transition_scores[pos-1, current_state, :])
forward[pos, current_state] += emission_scores[pos, current_state]

My intuition suggests that the forward algorithm is correct. I have derived the following formula (which we might put in the document to facilitate the comprenhension of the algorithm)

![logsumexp](https://cloud.githubusercontent.com/assets/4223580/8135809/e8d42dc0-1139-11e5-9658-ae1775010d58.png)

where we have:
   logsum( forward + transition_scores ) + emission_scores

**Comment by ramon-astudillo** [comment]
Yes, this has to do with the fact that the code was implemented with the structured predictors from day 3 in mind.
