### ISSUE TITLE
Windows users have codec problems when invoking pdb

### ISSUE THREAD

**Issue by miguelbalmeida** [LxMLS/lxmls-toolkit#53]
At least one Windows user reported having problems when adding the line "import pdb; pdb.set_trace()" to a file on Day 1. This would yield a codecs related error message.

Changing that to "import ipdb; ipdb.set_trace()" fixed the issue. This requires installing ipdb beforehand with the command "pip install ipdb", run from the command line.

We should test this on a Windows machine and, if confirmed, change the guide to add this remark for Windows users.

**Comment by ramon-astudillo** [comment]
latest versions of ipdb are problematic themselves. We should try to find a
specific solutio for that

**Comment by ramon-astudillo** [comment]
This no longer applies. ipdb is removed from the code-base for robustnes. pdb should be reliable in all platforms.
