### ISSUE TITLE
MrJob word count example doesn't work on windows

### ISSUE THREAD

**Issue by smiranda** [LxMLS/lxmls-toolkit#57]
For some reason, MrJob doesn't run the reducer step correcly on windows. This has been verified in several windows laptops during the labs. A quick fix is adding a combiner function implementation to the MRJob subclass, doing the same thing as the reducer:
```
def combiner(self, word, counts):
    yield (word, sum(counts))
```
I'm not sure why this works. Nevertheless, it has been verified in both mrjob v0.4.4 and v0.5.0-dev, on python Anaconda 2.7.9, 64bit.

**Comment by smiranda** [comment]
It's useful to say that this idea was inspired by the wordcount example shiped with mrjob, so perhaps this is the canonical way of specifying a MRJob subclass.

https://github.com/Yelp/mrjob/blob/master/mrjob/examples/mr_word_freq_count.py

**Comment by miguelbalmeida** [comment]
Apparently, making the mapper and reducer yield "w.lower()" instead of "w" is an easy hack to fix the issue. I think we should find a more appropriate solution but this hack might shed light on what the problem is.

Thanks to Sebastiao Miranda and Daniel Ferreira for figuring out this hack.

**Comment by ramon-astudillo** [comment]
This does not apply any more
