### ISSUE TITLE
svm is provided in student branch

### ISSUE THREAD

**Issue by bastings** [LxMLS/lxmls-toolkit#66]
(I'm making an issue so we don't forget for next year.)

The lab guide asks to implement SVM primal, but it is provided in the student branch in classifiers/svm.py.

If we remove it, solve.py should download the master version. Right now it does not do that.
Solve also downloads perceptron.py, but that is unnecessary since it is also already provided.

**Comment by ramon-astudillo** [comment]
This is an issue in the guide rather than in the toolkit.

**Comment by ramon-astudillo** [comment]
This is now solved on the guide. Closing it here.
