### ISSUE TITLE
Change to Python3

### ISSUE THREAD

**Issue by ramon-astudillo** [LxMLS/lxmls-toolkit#70]
Aside of the obvious reasons, Jupyter notebook in anaconda is giving more and more problems

**Comment by davidbp** [comment]
What problems?
Could you list the encountered problems?

**Comment by ramon-astudillo** [comment]
For people with anaconda the python2 kernel seems to be missing. In some cases (this is unclear) it refuses to use the kernel even if it is installed.

**Comment by dcferreira** [comment]
Is anyone handling this? I can look into it this or next week, if no one is doing it already.

**Comment by ramon-astudillo** [comment]
@dcferreira right now we need to solve a couple of more urgent issues.

https://github.com/LxMLS/lxmls-toolkit/issues/72

https://github.com/LxMLS/lxmls-toolkit/issues/73

then we can do this one.

**Comment by ramon-astudillo** [comment]
Thanks, 1st lxmls winter-school student up there ;-).

**Comment by davidbp** [comment]
I didnt have any problem for kernel missing using anaconda not for python 2 or python 3.

Do you think it might help to make a bit longer the part of installation of anaconda and how to set up everything in the guide?

Something like this:


#### create environment for the summerschool code

The following code will create an environment for python 3
```
conda create --name lxmls_student python=3.6
```

To enter into the environment write 
```
source activate lxmls_student
```

Once you are in the environment you can install the packages needed:
```
conda install matplotlib nltk scipy numpy
conda install pytorch torchvision -c pytorch
```

**Comment by pedrobalage** [comment]
I am porting the current code from develop to python3 ready (2.7, 3.5 and 3.6). This is important to pass all Tox tests for cross-platform compatibility. Is anyone also working on this?

**Comment by ramon-astudillo** [comment]
We will need to deal first with

* Notebooks for all days

* Unit tests from notebooks

Then we can start testing the Python3 compatibility. See

https://github.com/LxMLS/lxmls-toolkit/projects/1

Since we opened the project there is duplication of issues. I will close this here to avoid confusion. For Unit test / Python3 lest use your own 

https://github.com/LxMLS/lxmls-toolkit/issues/80

**Comment by ramon-astudillo** [comment]
Moved inside the LxMLS 2018 project https://github.com/LxMLS/lxmls-toolkit/issues/80
