### ISSUE TITLE
NOTEBOOK: Basic Tutorials

### ISSUE THREAD

**Issue by ramon-astudillo** [LxMLS/lxmls-toolkit#76]
Write exercise text and code for the Basic Tutorials day into a notebook under

   labs/notebooks/basic_tutorials/

use 

    labs/notebooks/non_linear_classifiers/

as reference

**Comment by MarianaAlmeida** [comment]
Done.
@ramon-astudillo 
@pedrobalage

**Comment by pedrobalage** [comment]
@MarianaAlmeida , do a Pull Request from your branch into master and put me as reviewer. I may take a look into it tomorrow.

**Comment by MarianaAlmeida** [comment]
@pedrobalage 
Fiz o pull request.
O branch contem este notebook e o notebook do dia2 - sequence models.
