### ISSUE TITLE
NOTEBOOK: Sequence Models

### ISSUE THREAD

**Issue by ramon-astudillo** [LxMLS/lxmls-toolkit#78]
Write exercise text and code for the Sequence Models day into a notebook under

labs/notebooks/sequence_models/

use

labs/notebooks/non_linear_classifiers/

as reference

**Comment by madrugado** [comment]
could you add more details on that?

**Comment by ramon-astudillo** [comment]
Hi Valentin :). We have not yet created the monitor's team for this year, but you are welcome to contribute as an outsider if you want to. Just fork and do PRs.

The idea here is the same as in the other days. Create notebooks with the text and code of the exercises of each day. This one corresponds to the 4th day, sequence models. The most recent version of the guide can be found here

    http://lxmls.it.pt/2018/LxMLS_guide_2018.pdf

**Comment by MarianaAlmeida** [comment]
Just started this notebook on branch: 
`
feature/notebook_day0_day2
`
@ramon-astudillo 
@madrugado

**Comment by MarianaAlmeida** [comment]
Done
@ramon-astudillo

**Comment by ramon-astudillo** [comment]
@MarianaAlmeida can you remove `day0_` from the folder name i.e. `day0_basic_tutorial/Exercises_0.10_to_0.15.ipynb`
