### ISSUE TITLE
Unit Tests and cross platform compatibility

### ISSUE THREAD

**Issue by pedrobalage** [LxMLS/lxmls-toolkit#80]
Build unit tests for each day/algorithm and check for compatibility across different python version (2.7, 3.5, 3.6).

**Comment by ramon-astudillo** [comment]
The objective here is

- [ ] Derive unit tests from the notebooks similarly to `labs/convert_notebooks.sh` is used to derive python scripts from days.

- [ ] Pass all tests for Python3 as well as Python2

For this is necessary first to solve all the NOTEBOOK cards in

https://github.com/LxMLS/lxmls-toolkit/projects/1

@davidbp can you assign yourself some of those cards?. @pedrobalage maybe you can help with the other ones?.

**Comment by pedrobalage** [comment]
I finished to merge the master in the develop and convert for python3 compatible. This work is in my fork. So far, the tests are running as below.

Next stage is to check the notebooks.

```
$ python3 runtests.py 
=============================================== test session starts ================================================
platform linux -- Python 3.5.2, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/ppb/Projects/Labs/lxmls-toolkit, inifile: tox.ini
collected 34 items                                                                                                 

test_day1.py F...........                                                                                    [ 35%]
test_day2.py ..........                                                                                                                                                           [ 64%]
test_day3.py ....                                                                                                                                                                 [ 76%]
test_day4.py ........                                                                                                                                                             [100%]
================================================================================ short test summary info ================================================================================
FAIL test_day1.py::test_naive_bayes_simple_dataset

======================================================================================= FAILURES ========================================================================================
____________________________________________________________________________ test_naive_bayes_simple_dataset ____________________________________________________________________________

sd = <lxmls.readers.simple_data_set.SimpleDataSet object at 0x7f037183d3c8>

    def test_naive_bayes_simple_dataset(sd):
        np.random.seed(4242)
    
        gnb = gnbc.GaussianNaiveBayes()
        params_nb_sd = gnb.train(sd.train_X, sd.train_y)
        y_pred_train = gnb.test(sd.train_X, params_nb_sd)
        acc_train = gnb.evaluate(sd.train_y, y_pred_train)
>       assert abs(acc_train - 0.88) < tolerance
E       assert 0.020000000000000018 < 1e-05
E        +  where 0.020000000000000018 = abs((0.9 - 0.88))

test_day1.py:38: AssertionError
```

**Comment by ramon-astudillo** [comment]
Can you help us do the NOTEBOOK cards? (see my comment above). We might change the tests anyway if we are going to derive them from the notebooks.

**Comment by pedrobalage** [comment]
I am going to sync day by day the tests and the notebook cards. I am going to start with day0 (basic tutorials).

I am a little sceptical about using notebooks for unit testing. We may use them for checking if the output is the one we expect for the exercises. In the other hand, unit tests should test the function level of the library.

**Comment by ramon-astudillo** [comment]
The idea is not to use directly the notebooks but rather derive the python code of the unit-tests automatically from the notebooks. Right now `labs/convert_notebooks.sh` converts notebooks to python code. It is an open question if this will work but it will reduce the effort in keeping the tests up to date when we modify the days. We will need to have the notebooks anyway.

**Comment by pedrobalage** [comment]
@ramon-astudillo  and @kepler , a short status about this task:

I've been working for the last days on this task, but there was some problems I found which is taking me a longer time to finish this.
   
- [ ]  Python 2 and Python 3 have different results for NaiveBayes. The problem may be the numpy seed, but I am investigating.
- [ ] Python 3.5 and python 3.6 are given different results for syntax and parsing tests. I am trying to address this problem which I believe is due to a different dict implementation for python 3.6 (https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-compactdict).

I hope to finish this issues on this Saturday and open the pull request.

Pedro

**Comment by ramon-astudillo** [comment]
@pedrobalage  if this results in extra complications, lets set as objective Python compatibility up to Python 3.5.

**Comment by dcferreira** [comment]
Is something missing to solve this issue?

**Comment by pedrobalage** [comment]
@ramon-astudillo , I suggest to keep the tests separated from the notebooks for the following reasons:

* The tests were designed from the notebooks. As we do not plan to change the exercises often, so we should not change the notebooks neither the tests often too.
* The notebooks allow things we could not achieve in a testing environment, like plotting functions, debugging with pdb and executing notebook commands (%command).
* The tests run with pytest suite, which allow us to build independent tests which are executed in parallel.  Either we add pytest to notebooks, which is a bad idea, or the tests should not use pytest suite, which is also a bad idea.
* The tests were designed to check if the values of the exercises are consistent in all executions for different environments. For speed and simplicity, we adopted few interaction for heavy algorithms. If we intend to use notebooks, the tests should take at least 10x more time to run.

I believe we may have a different idea for the reason of these tests. In my opinion, the tests should guarantee that any modification of the source code will not affect the answer from the exercises. This is the objective of the unit tests in my opinion. 

Another way to see, it is that the tests should guarantee that any experiment in the notebooks should have the same result in any python version for any OS. This is more like consistency and I believe this is what you would like. We could try to make some testing tool for this, but I don't think this should be in the unit testing since it is not testing changes in the code, but in the notebooks.

**Comment by ramon-astudillo** [comment]
ok, lets leave it as it is. We will need to change this if we add or change more days.
