### ISSUE TITLE
Small problems with python basics notebook

### ISSUE THREAD

**Issue by venelink** [LxMLS/lxmls-toolkit#94]
Hi,

I have noticed few small problems with python basics notebook:

0.2

There is a difference between the code in the lab guide and the code in the notebook. The "a +=1" line should NOT be indented, according to the guide, and should thus lead to infinite cycle. In the notebook the code is the same as the example right above it.

0.3 Exceptions

More of a usage case comment, than actual error - in order to actually get ValueError, I need to specifically insert something like "a" (the string with the quotes). If I just insert the character a (without quotes), the notebook interprets it as a variable and I get NameError for undefined variable rather than the value error and the exception. 

0.6 and 0.7 

The code for 0.6 and 0.7 is double (there are two 0.6 sections, the first one having the code for both 0.6 and 0.7).

**Comment by dcferreira** [comment]
Can you make a pull request for these changes?

**Comment by venelink** [comment]
I tried to do a pull request with a fixed version for the 0.3, 0.6, 0.7 issues.
I'm still learning how to handle all the details of the git, so I hope I didn't mess something up :).

**Comment by ramon-astudillo** [comment]
Thanks just change the PR to develop and we will merge and close

**Comment by ramon-astudillo** [comment]
Fixed by https://github.com/LxMLS/lxmls-toolkit/pull/95
